set -x PATH /usr/local/bin $PATH
set -x PATH /usr/local/sbin $PATH
set -x PATH /usr/local/share/npm/bin $PATH
set -x PATH /usr/local/share/python $PATH
set -x PATH $HOME/.dotfiles/bin $PATH
set -x PATH $HOME/.rbenv/plugins/ruby-build/bin $PATH
set -x PATH $HOME/.rbenv/bin $PATH
set -x PATH $HOME/.rbenv/shims $PATH
set -x PATH $HOME/.misc/git-achievements $PATH
